# Generated by Django 4.1.6 on 2023-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0002_rename_nom_utilisateur_cominauteur_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominauteur',
            name='NB_GSM',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
