# Generated by Django 4.1.6 on 2023-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0003_alter_cominauteur_nb_gsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominauteur',
            name='NB_GSM',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
