# Generated by Django 4.1.6 on 2023-02-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0004_alter_cominauteur_nb_gsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cominauteur',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='composteur',
            name='mot_de_passe',
        ),
    ]
