# Generated by Django 4.1.6 on 2023-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0005_remove_cominauteur_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominauteur',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
