# Generated by Django 4.1.7 on 2023-03-09 23:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0006_alter_cominauteur_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='greener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('NB_GSM', models.CharField(max_length=20, null=True)),
                ('pseudo', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='cominauteur',
        ),
        migrations.RemoveField(
            model_name='composteur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='composteur',
            name='username',
        ),
        migrations.AddField(
            model_name='composteur',
            name='NB_GSM',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='e_mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='composteur',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='composteur',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='pseudo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
