# Generated by Django 4.1.7 on 2023-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0008_alter_composteur_nb_gsm_alter_greener_nb_gsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteur',
            name='desponible',
            field=models.BooleanField(null=True),
        ),
    ]
