# Generated by Django 4.1.7 on 2023-04-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0011_alter_greener_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='image',
            field=models.ImageField(blank=True, default='profil.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='greener',
            name='image',
            field=models.ImageField(blank=True, default='profil.png', null=True, upload_to='profile_pics'),
        ),
    ]
