# Generated by Django 4.1.7 on 2023-04-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0012_alter_composteur_image_alter_greener_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
