# Generated by Django 4.1.7 on 2023-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0016_remove_composteur_id_alter_composteur_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
