# Generated by Django 4.1.7 on 2023-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0017_alter_composteur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greener',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
