# Generated by Django 4.1.7 on 2023-04-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0018_alter_greener_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composteur',
            old_name='desponible',
            new_name='disponible',
        ),
    ]
