# Generated by Django 4.1.7 on 2023-04-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0020_alter_composteur_image_alter_greener_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greener',
            name='composteur',
        ),
    ]
