# Generated by Django 4.1.7 on 2023-05-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0021_remove_greener_composteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='composteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.composteur'),
        ),
    ]
