# Generated by Django 4.1.7 on 2023-05-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0023_remove_greener_id_alter_greener_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteur',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
