# Generated by Django 4.1.7 on 2023-05-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0024_composteur_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
