# Generated by Django 4.1.7 on 2023-05-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0025_alter_composteur_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='greener',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
