# Generated by Django 4.1.7 on 2023-05-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0026_alter_composteur_image_alter_greener_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greener',
            name='image',
            field=models.ImageField(upload_to='profile_pics\\profil.png'),
        ),
    ]
