# Generated by Django 4.1.7 on 2023-05-23 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creer_compte', '0030_alter_greener_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeneur',
            fields=[
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('NB_GSM', models.CharField(max_length=100, null=True)),
                ('pseudo_G', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('portfeuille', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='greener',
            name='composteur',
        ),
        migrations.RenameField(
            model_name='composteur',
            old_name='disponible',
            new_name='Validation',
        ),
        migrations.RenameField(
            model_name='composteur',
            old_name='pseudo',
            new_name='pseudo_C',
        ),
    ]
