# Generated by Django 4.1.7 on 2023-04-27 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_order_customer_order_greener'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grenneur', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('animaux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('azoté', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carboné', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disponible', models.DateField()),
                ('heure_disponible', models.TimeField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='deshet',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
