# Generated by Django 4.1.7 on 2023-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_grenneur_transaction_greeneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='totale_point',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
