# Generated by Django 4.1.7 on 2023-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_transaction_totale_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valider',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
