# Generated by Django 4.1.7 on 2023-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_transaction_recipient_transaction_composteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
