# Generated by Django 4.1.7 on 2023-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_transaction_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valider',
            field=models.BooleanField(null=True),
        ),
    ]
