# Generated by Django 4.1.7 on 2023-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_transaction_valider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
