# Generated by Django 4.1.7 on 2023-05-23 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_transaction_valider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Déshets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animaux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('azoté', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carboné', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disponible', models.DateField()),
                ('heure_disponible', models.TimeField()),
                ('totale_point', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('valider', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='composteur',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='greeneur',
        ),
    ]
