# Generated by Django 4.1.7 on 2023-05-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_déshets_remove_transaction_composteur_and_more'),
        ('composteur', '0007_alter_transactioncoins_identification'),
        ('creer_compte', '0032_delete_greener_greeneur_pseudo_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='déshets',
            name='pseudo_C',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.composteur'),
        ),
        migrations.AddField(
            model_name='déshets',
            name='pseudo_G',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.greeneur'),
        ),
    ]
