# Generated by Django 4.1.7 on 2023-05-01 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creer_compte', '0023_remove_greener_id_alter_greener_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale_point', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('greeneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.greener')),
            ],
        ),
    ]
