# Generated by Django 4.1.7 on 2023-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteur', '0002_transactioncoins_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncoins',
            name='Identification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
