# Generated by Django 4.1.7 on 2023-05-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_transaction_quantite'),
        ('composteur', '0003_alter_transactioncoins_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncoins',
            name='Identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.transaction'),
        ),
    ]
