# Generated by Django 4.1.7 on 2023-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteur', '0004_alter_transactioncoins_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncoins',
            name='greeneur',
        ),
    ]
