# Generated by Django 4.1.7 on 2023-05-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composteur', '0005_remove_transactioncoins_greeneur'),
        ('creer_compte', '0031_greeneur_remove_greener_composteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncoins',
            name='pseudo_G',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.greeneur'),
        ),
    ]
